### ISSUE TITLE
Write a better ReadMe

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/SelfUp#18]
we need to make ReadMe more specific and clear. considering Visual components, Figma link for somebody who want to contribute in UI and UX and also putting a code of conduct.

### To-Do:

- [ ] add UI & UX design link
- [ ] add Trello link for people who wanna know more about running tasks
- [ ] add project mockups
- [ ] use headings, emojis and other formatting options
- [ ] write a good explanation for the project (first thing after first heading)
- [x] add project architecture, database structure and directory structure
