### ISSUE TITLE
Connect dashboard axios connection to Back-end

### ISSUE THREAD

**Issue by edrisranjbar** [edrisranjbar/SelfUp#27]
Now Axios is going to connect straight to our Rest-full API, which causes errors and it also it's not secure because user in front-end can basically manipulate data at any state. what we can do is to connect axios to back-end flask application. in this case we need a bunch of routes for dashboard.

### To-Do:

- [x] change api routes in axios to back-end ip address and port
- [x] add all required routes for "/dashboard"
- [x] before processing any request and sending to API, check if user is authenticated
- [x] user should only be able to access to **only** his/her own data
